/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante.ui;

import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;
import restaurante.controladores.CGestionDePedidos;
import restaurante.controladores.CSeleccionDeUPP;
import restaurante.dominio.Gestor;
import restaurante.dominio.Sistema;
import restaurante.dominio.UPP;
import restaurante.dominio.Usuario;
import restaurante.utils.Utilidades;
import restaurante.vistas.VSeleccionDeUPP;

/**
 *
 * @author alumnoFI
 */
public class FrameSeleccionDeUPP extends javax.swing.JFrame implements VSeleccionDeUPP {

    private Gestor gestor;
    private UPP upp;
    private CSeleccionDeUPP controlador;

    public FrameSeleccionDeUPP(Gestor ges) {
        initComponents();
        //pasar al controlador, consulta si tiene upp, le dice a la vista continuar o ir a gestion
        setLocationRelativeTo(null);
        
        this.gestor = ges;
        controlador = new CSeleccionDeUPP(gestor, this);
        setTitle("Bienvenido: " + gestor.getNombre());
        chequeo();
               

    }
    
    private void chequeo(){
        controlador.chequearYaRegistrado(gestor);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        cboUPP = new javax.swing.JComboBox();
        registrarseEnUPP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel3.setText("UPP's:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 40, 50, 14);

        getContentPane().add(cboUPP);
        cboUPP.setBounds(80, 30, 240, 30);

        registrarseEnUPP.setText("Registrarse");
        registrarseEnUPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseEnUPPActionPerformed(evt);
            }
        });
        getContentPane().add(registrarseEnUPP);
        registrarseEnUPP.setBounds(120, 80, 140, 30);

        setBounds(0, 0, 393, 198);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        controlador.cerrar();
       
    }//GEN-LAST:event_formWindowClosing

    private void registrarseEnUPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseEnUPPActionPerformed
        // TODO add your handling code here:
        registrarseEnUPP();
    }//GEN-LAST:event_registrarseEnUPPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboUPP;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton registrarseEnUPP;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cerrarVentana(){
        dispose();
    }
    
    @Override
    public void registrarseEnUPP() {
        this.upp = (UPP) cboUPP.getSelectedItem();
        controlador.registrarseEnUPP(this.upp);
        
    }

    @Override
    public void yaRegistrado(UPP uppRecibida) {
        this.upp = uppRecibida;
        
    }

    @Override
    public void irAGestion() {
        
        FrameGestionarPedidos frame = new FrameGestionarPedidos(gestor, upp);
        frame.setVisible(true);
        Sistema.getInstancia().getsServicios().addObserver(frame);
    }

    @Override
    public void cargarCombo() {
       Utilidades.cargarComboUpp(cboUPP);
    }

   @Override
    public void error(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }
    
    
    
}
