/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante.ui;

import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;
import restaurante.controladores.CGestionDePedidos;
import restaurante.dominio.Gestor;
import restaurante.dominio.UPP;
import restaurante.dominio.Usuario;
import restaurante.utils.Utilidades;
import restaurante.vistas.VGestionDePedidos;

/**
 *
 * @author alumnoFI
 */
public class FrameGestionarPedidos extends javax.swing.JFrame implements VGestionDePedidos, Observer {

    private Gestor gestor;
    private UPP upp;
    private CGestionDePedidos controlador;

    

    public FrameGestionarPedidos(Gestor gestor, UPP upp) {
         initComponents();

        setLocationRelativeTo(null);
        
        this.gestor = gestor;
        this.upp = upp;
        controlador = new CGestionDePedidos(this, gestor, upp);
        mostrarTitulo();
        mostrarPedidos();
    }
    
    private void mostrarTitulo() {
        
        setTitle("Bienvenido a la UPP: " + upp.getNombre() + " - " + gestor.getNombre());
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        lstPedidos = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstPedidosTomados = new javax.swing.JList();
        btnFinalizarPedido = new javax.swing.JButton();
        btnTomarPedido1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jScrollPane2.setViewportView(lstPedidos);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 40, 570, 180);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Pedidos Pendientes:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 170, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Pedidos Tomados:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 240, 220, 22);

        jScrollPane3.setViewportView(lstPedidosTomados);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 260, 570, 180);

        btnFinalizarPedido.setText("Finalizar Pedido");
        btnFinalizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(btnFinalizarPedido);
        btnFinalizarPedido.setBounds(600, 320, 170, 50);

        btnTomarPedido1.setText("Tomar Pedido");
        btnTomarPedido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTomarPedido1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTomarPedido1);
        btnTomarPedido1.setBounds(600, 90, 170, 50);

        setBounds(0, 0, 860, 502);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        controlador.cerrarVentana();
        
    }//GEN-LAST:event_formWindowClosing

    private void btnTomarPedido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTomarPedido1ActionPerformed
        // TODO add your handling code here:
        controlador.tomarPedido(lstPedidos.getSelectedValue());
    }//GEN-LAST:event_btnTomarPedido1ActionPerformed

    private void btnFinalizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarPedidoActionPerformed
        // TODO add your handling code here:
        controlador.finalizarPedido(lstPedidosTomados.getSelectedValue());
    }//GEN-LAST:event_btnFinalizarPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizarPedido;
    private javax.swing.JButton btnTomarPedido1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList lstPedidos;
    private javax.swing.JList lstPedidosTomados;
    // End of variables declaration//GEN-END:variables

    
     private void mostrarPedidos() {
        lstPedidos.setListData(upp.getPedidos().toArray());
        lstPedidosTomados.setListData(gestor.getPedidos().toArray());
    }
    
     
    @Override
    public void error(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }

    @Override
    public void actualizar() {
        
        mostrarPedidos();
    }

    @Override
    public void cerrar() {
        dispose();
        new LoginGestorDialog(null, false).setVisible(true);
    }

    @Override
    public void update(Observable o, Object arg) {
        actualizar();
    }

}
